# Gunakan base image Node.js
FROM node:20

# Set working directory
WORKDIR /app

# Copy dependency files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy semua source code
COPY . .

# Build aplikasi
RUN npm run build

# Expose port NestJS
EXPOSE 3000

# Start aplikasi
CMD ["node", "dist/main"]
