version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://myuser:mypassword@db:3306/mydb
    ports:
      - "3000:3000"
    command: npm run start:dev

volumes:
  mysql_data:
